### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [sumansrid/prj-rev-bwfs-dasmoto#5]
https://github.com/sumansrid/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's/Resources/CSS/style.css#L1-L7

This is not readable, much less maintainable.

Write your CSS rules like so even if they only contain a single style. 

```css
selector {
  property: value;
  property: value;
}
```
